# Generated by Django 5.0.6 on 2024-07-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aerosoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fragancia', models.CharField(max_length=20)),
                ('stock', models.IntegerField()),
                ('fecha_vencimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Textiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fragancia', models.CharField(max_length=20)),
                ('stock', models.IntegerField()),
                ('fecha_vencimiento', models.DateField()),
            ],
        ),
    ]
