# Generated by Django 5.0.6 on 2024-07-03 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aerosoles',
            old_name='fecha_vencimiento',
            new_name='fecha',
        ),
    ]
