# Generated by Django 5.0.6 on 2024-07-03 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_rename_fecha_vencimiento_aerosoles_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aerosoles',
            old_name='fecha',
            new_name='fecha_vencimiento',
        ),
    ]
