# Generated by Django 5.0.6 on 2024-07-04 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_cliente_delete_clientes_delete_infoclientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles'),
        ),
    ]
