# Generated by Django 5.0.6 on 2024-07-04 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_cliente_fecha_nacimiento_cliente_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
